name = "power-in-the-prize-props"
main = "src/index.js"
compatibility_date = "2026-08-01"

[triggers]
crons = ["*/10 * * * *", "0 6,23 * * *"]

[[kv_namespaces]]
binding = "PROPS_DATA"
id = "791e78dd86124d17873a367e48dd2a00"
